In [2]:

import numpy as np


In [6]:
#Concepts Used
x = np.zeros([100,100])#Initailize a 2D array of zeros
x = np.zeros_like(x)#Initailize a 2D array with having d-type and shape similar to previous one.
x = np.ones([100,100])#Initailize a 2D array of ones
x = np.ones_like(x)

In [8]:
x=np.arange(10,100,5)#Initialize a operator which generates value starting from 10 to 100 with step size of 5
x

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [9]:
x=np.random.uniform(low=0,high=1,size=(100,100))#generate random numbers from the uniform distribution
x=np.random.randn(100,100) #generate random numbers from the normal gaussian distribution
x=np.random.normal(loc=0,scale=1,size=(100,100)) #generate random numbers from the gaussian distribution


In [11]:
arranged_100= np.arange(0,100,1).reshape([10,10])
arranged_100

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [12]:
cropped_slice=arranged_100[5:10,0:5]
cropped_slice

array([[50, 51, 52, 53, 54],
       [60, 61, 62, 63, 64],
       [70, 71, 72, 73, 74],
       [80, 81, 82, 83, 84],
       [90, 91, 92, 93, 94]])

In [13]:
print(cropped_slice + 10)

[[ 60  61  62  63  64]
 [ 70  71  72  73  74]
 [ 80  81  82  83  84]
 [ 90  91  92  93  94]
 [100 101 102 103 104]]


In [14]:
x= np.zeros([5,5])
x[np.arange(5),np.arange(5)]=1
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
#Image as as 3-D Array
#Numpy array has some number of rows and columns and 3 Dimensions(red,green,blue).
#We can Image proceesing by 3 libraries in python. #matplotlib#openCV#Pillow
#We will see here Pillow.

from PIL import Image
img = Image.open('pexels-zett-foto-672142.jpg')
print(img)

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=7200x4800 at 0x19317B6B2B0>


In [4]:
img.show()

In [ ]:
#.new function---we can define new image from this function
# syntax Image.new(mode,size,colour)  mode=RGB,RGBA,.... size= any tuple of your choice , colour= any tuple of size 3 of your choice

img = Image.new('RGB',(400,500),(255,0,0))
img.show()
img = Image.new('RGB',(400,500),'Yellow')# we can simply give color name also.
img.show()



img = Image.open('pexels-zett-foto-672142.jpg')
print(img)


In [5]:
img = Image.open('pexels-zett-foto-672142.jpg')
print(img)

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=7200x4800 at 0x19316E75240>


In [7]:
img = img.rotate(90,expand=True) #for rotating the image
img.show()                       #expand=True to get image without loss of data

In [12]:
img = img.rotate(60,expand=True,fillcolor="Green",resample=Image.BICUBIC,center=(100,100))
img.show()                                          

In [15]:
img = img.rotate(60,expand=True,fillcolor="Green")#fillcolor = to give background color
img.show()

In [ ]:
img = img.rotate(60,expand=True,fillcolor="Green",resample=Image.BICUBIC) #resample = to give full quality image
img.show()  

In [16]:
img = img.rotate(60,expand=True,fillcolor="Green",resample=Image.BICUBIC,center=(100,100)) #center = to change center of rotation
img.show()  

In [20]:
img = Image.open('pexels-zett-foto-672142.jpg')
print(img.width,img.height)
img.show()

7200 4800


In [21]:
img = img.resize((int(img.width/2),int(img.height/2))) #to change width and height of image
print(img.width,img.height)
img.show()

3600 2400


In [22]:
img = img.resize((int(img.width*2),int(img.height*2)),box=(20,20,100,100)) #box is used to scale the image with particular coordinate and present it by choicr of your size
print(img.width,img.height)
img.show()

7200 4800


In [24]:
#for blending 2 images, both the images should be of same size
#syntax: (img1,img2,alpha)...alpha is interpolating constant, if we give alpha as 0...then img2 will be considered as transparent and if as 1 then img1 will be considered as transparent
#for ideal result give alpha as 0.5

img1 = Image.open('pexels-zett-foto-672142.jpg')
img2 = Image.open('pexels-zett-foto-672142.jpg')
print(img1)
print(img2)


<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=7200x4800 at 0x19316E759C0>
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=7200x4800 at 0x19316FF1C30>


In [25]:
img = Image.blend(img1,img2,alpha=0.5)
img.show()

In [26]:
img = Image.open('pexels-zett-foto-672142.jpg')
print(img)

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=7200x4800 at 0x1934646F040>


In [27]:
imgcrop= img.crop(box= (20,20,200,200)) #to crop the particular part of the image for this we have to define box(point of start, point of end , width of box, height of box)
imgcrop.show()